# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Open In Order To...
email: Joe@sparcopen.org
description: What concrete benefits can be realized by making scholarly outputs openly available?
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://openinorder.to/" # the base hostname & protocol for your site PRODUCTION: http://openinorder.to/
gems:
  - jekyll-redirect-from
plugins:
  - jekyll-seo-tag

# SEO settings

twitter:
  username: sparc_na
logo: "/favicon.ico" # site wide logo for use on social settings
facebook:
 publisher: sparcopen
lang: en_US

# Social settings
github_username: sparcopen/open-to
twitter_username: sparc_na

# Build settings
markdown: kramdown

# Layout settings
home-link-in-menu: false #true or false
front-page-posts: 24 #maximum number of posts to show on front page
